### ISSUE TITLE
Recipes - Add examples for how to use these components.

### ISSUE THREAD

**Issue by blesh** [Netflix/ember-cli-nf-graph#3]
A top priority for since this component library is really a DSL of sorts, is putting out some sort of "recipe" list or pages that show various ways to use the components to create various effects.

A few ideas for this are:

- Basic line graph
- Creating area graphs and stacked area graphs
- "Hover data" on mouse moves - displaying data nearest the mouse on the graph
- Shared line/area selection - sharing selected data between multiple graphs
- Brush selection - adding brush selection to a graph or graphs with nf-brush-selection
- Using nf-bars
- Mixing nf-bars and line or area graphs
- Creating custom graph components
- Using "primitive" components (nf-svg-rect for example)
- Customizing axis ticks with tickFilter, etc 

attn @jeff3dx  and @jayphelps - I could really use your help here.

**Comment by jeff3dx** [comment]
I picked up this one.
